#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ] # USER MUST BE ROOT

### INSTALL THIS SYSTEM ###
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown www-data:www-data "$appdir" -R

### RENAME FETCH CGI ###
cd "$appdir"
mv "fetch" "fetch.cgi"

### PULL DATA ###
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents.git"
chown www-data:www-data "$contentsdir" -R

echo "call fetch.cgi from GitHub"
